from .base import *
import os

""" BI 19 """

BI_19_DG = COMMON_DG

BI_19_DIRNAME = "BI_19"
BI_19_ORIGINAL_Q_PRE = f"{ORIGINAL_QUERY_PREFIX}/{BI_19_DIRNAME}"
BI_19_OPTIMIZED_Q_PRE = f"{OPTIMIZED_QUERY_PREFIX}/{BI_19_DIRNAME}"
BI_19_ORIGINAL_L_PRE = f"{ORIGINAL_LOG_PREFIX}/{BI_19_DIRNAME}"
BI_19_OPTIMIZED_L_PRE = f"{OPTIMIZED_LOG_PREFIX}/{BI_19_DIRNAME}"

BI_19_DG_OPTIMIZED = f"{BI_19_OPTIMIZED_Q_PRE}/data_graph.txt"

for e in [
    BI_19_ORIGINAL_Q_PRE,
    BI_19_OPTIMIZED_Q_PRE,
    BI_19_ORIGINAL_L_PRE,
    BI_19_OPTIMIZED_L_PRE,
]:
    if not os.path.exists(e):
        os.makedirs(e)
