from .base import *
import os

""" BI 13 """

BI_13_DG = COMMON_DG
BI_13_DG_OPTIMIZED = COMMON_DG_OPTIMIZED

BI_13_DIRNAME = "BI_13"
BI_13_ORIGINAL_Q_PRE = f"{ORIGINAL_QUERY_PREFIX}/{BI_13_DIRNAME}"
BI_13_OPTIMIZED_Q_PRE = f"{OPTIMIZED_QUERY_PREFIX}/{BI_13_DIRNAME}"
BI_13_ORIGINAL_L_PRE = f"{ORIGINAL_LOG_PREFIX}/{BI_13_DIRNAME}"
BI_13_OPTIMIZED_L_PRE = f"{OPTIMIZED_LOG_PREFIX}/{BI_13_DIRNAME}"

for e in [
    BI_13_ORIGINAL_Q_PRE,
    BI_13_OPTIMIZED_Q_PRE,
    BI_13_ORIGINAL_L_PRE,
    BI_13_OPTIMIZED_L_PRE,
]:
    if not os.path.exists(e):
        os.makedirs(e)
