from .base import *
import os

""" BI 15 """

BI_15_DG = COMMON_DG

BI_15_DIRNAME = "BI_15"
BI_15_ORIGINAL_Q_PRE = f"{ORIGINAL_QUERY_PREFIX}/{BI_15_DIRNAME}"
BI_15_OPTIMIZED_Q_PRE = f"{OPTIMIZED_QUERY_PREFIX}/{BI_15_DIRNAME}"
BI_15_ORIGINAL_L_PRE = f"{ORIGINAL_LOG_PREFIX}/{BI_15_DIRNAME}"
BI_15_OPTIMIZED_L_PRE = f"{OPTIMIZED_LOG_PREFIX}/{BI_15_DIRNAME}"

BI_15_DG_OPTIMIZED = f"{BI_15_OPTIMIZED_Q_PRE}/data_graph.txt"

for e in [
    BI_15_ORIGINAL_Q_PRE,
    BI_15_OPTIMIZED_Q_PRE,
    BI_15_ORIGINAL_L_PRE,
    BI_15_OPTIMIZED_L_PRE,
]:
    if not os.path.exists(e):
        os.makedirs(e)
