from .base import *
import os

""" BI 10 """

BI_10_DG = COMMON_DG

BI_10_DIRNAME = "BI_10"
BI_10_ORIGINAL_Q_PRE = f"{ORIGINAL_QUERY_PREFIX}/{BI_10_DIRNAME}"
BI_10_OPTIMIZED_Q_PRE = f"{OPTIMIZED_QUERY_PREFIX}/{BI_10_DIRNAME}"
BI_10_ORIGINAL_L_PRE = f"{ORIGINAL_LOG_PREFIX}/{BI_10_DIRNAME}"
BI_10_OPTIMIZED_L_PRE = f"{OPTIMIZED_LOG_PREFIX}/{BI_10_DIRNAME}"

BI_10_DG_OPTIMIZED = f"{BI_10_OPTIMIZED_Q_PRE}/data_graph.txt"

for e in [
    BI_10_ORIGINAL_Q_PRE,
    BI_10_OPTIMIZED_Q_PRE,
    BI_10_ORIGINAL_L_PRE,
    BI_10_OPTIMIZED_L_PRE,
]:
    if not os.path.exists(e):
        os.makedirs(e)
