from .base import *
import os

""" BI 4 """

BI_4_DG = COMMON_DG
BI_4_DG_OPTIMIZED = COMMON_DG_OPTIMIZED

BI_4_DIRNAME = "BI_4"
BI_4_ORIGINAL_Q_PRE = f"{ORIGINAL_QUERY_PREFIX}/{BI_4_DIRNAME}"
BI_4_OPTIMIZED_Q_PRE = f"{OPTIMIZED_QUERY_PREFIX}/{BI_4_DIRNAME}"
BI_4_ORIGINAL_L_PRE = f"{ORIGINAL_LOG_PREFIX}/{BI_4_DIRNAME}"
BI_4_OPTIMIZED_L_PRE = f"{OPTIMIZED_LOG_PREFIX}/{BI_4_DIRNAME}"

for e in [
    BI_4_ORIGINAL_Q_PRE,
    BI_4_OPTIMIZED_Q_PRE,
    BI_4_ORIGINAL_L_PRE,
    BI_4_OPTIMIZED_L_PRE,
]:
    if not os.path.exists(e):
        os.makedirs(e)
