from .base import *
import os

""" IC 12 """

IC_12_DG = COMMON_DG

IC_12_DIRNAME = "IC_12"
IC_12_ORIGINAL_Q_PRE = f"{ORIGINAL_QUERY_PREFIX}/{IC_12_DIRNAME}"
IC_12_OPTIMIZED_Q_PRE = f"{OPTIMIZED_QUERY_PREFIX}/{IC_12_DIRNAME}"
IC_12_ORIGINAL_L_PRE = f"{ORIGINAL_LOG_PREFIX}/{IC_12_DIRNAME}"
IC_12_OPTIMIZED_L_PRE = f"{OPTIMIZED_LOG_PREFIX}/{IC_12_DIRNAME}"

IC_12_DG_OPTIMIZED = f"{IC_12_OPTIMIZED_Q_PRE}/data_graph.txt"

for e in [
    IC_12_ORIGINAL_Q_PRE,
    IC_12_OPTIMIZED_Q_PRE,
    IC_12_ORIGINAL_L_PRE,
    IC_12_OPTIMIZED_L_PRE,
]:
    if not os.path.exists(e):
        os.makedirs(e)
